# Generated by Django 3.0.1 on 2022-03-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_address',
            new_name='email',
        ),
    ]
